version: '3.1'
services:
  game:
    build: .
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - LGSM_GAMESERVERNAME=csgoserver
      - LGSM_UPDATEINSTALLSKIP=UPDATE
    volumes:
      - C:\path\to\maps:/home/linuxgsm/linuxgsm/serverfiles/csgo/maps